### PR TITLE
Update Atari-Jaguar.md

### PR DESCRIPTION
**Pull request by Unknown-programer**
Atari now has a console for sale. So technically it is back in the video game console market

### CODE REVIEW

**Comment by cmitu** [comment]
Just because it has the 'Atari' name, doesn't mean is the same company. See some history https://en.wikipedia.org/wiki/Atari_SA. It is not - by far - the same company that produced the games, consoles and computers back in the day, to which this doc pages refer.

 As for the 'back in the video game console market', that remains to be seen, the VCS doesn't have any market share and it's been sold mostly to the enthusiastic and nostalgic Atari fans that backed up their Indiegogo financing campaign.

I appreciate the enthusiasm, but I'm not going to include the changes.

**Comment by Unknown-programer** [comment]
ok

**Comment by Unknown-programer** [comment]
Are these changes acceptable?

**Comment by cmitu** [comment]
The 1st modification no - the CD is just an add-on for the Jaguar, not a _new_ console.

The 2nd one, probably - but I'd like to 
* include the forum post with the Pi4 experiments, just so users can find the original information and configurations more easily. 

* please capitalize the `pi` in _pi4_.
> but some games will run full speed on an overclocked **Pi4**

* leave some of the original recommenendation info (_isn't recommended for Raspberry Pi_ I think should still be kept, alongside the Pi4 info)

**Comment by cmitu** [comment]
I've added the info about the Pi4 manually in https://github.com/RetroPie/RetroPie-Docs/commit/6ba856092f2aeb1a3f01dfe9c1b24da1e6c1266a.

**Pull request closed without merging**
