### PR TITLE
Update Saturn.md

### PR DESCRIPTION
**Pull request by Unknown-programer**
We are on Pi4 now so I think this needs to be updated

### CODE REVIEW

**Comment by cmitu** [comment]
Looks ok, thanks.

NOTE: I think your editor is configured to automatically add a newline at the end of the file, this adds un-necessary changes in the diff. Can you try to disable this behavior ?

**Comment by cmitu** [comment]
I don't think there's such setting in Github. Are you using the web interface to edit the files directly ?

**Comment by Unknown-programer** [comment]
Yes

**Comment by cmitu** [comment]
Then I don't know. Just make sure you don't add any extra lines at the end of the file in this case.

**Pull request merged**
