### PR TITLE
Updated/restructured Memory Split page with Pi 4 information.

### PR DESCRIPTION
**Pull request by dankcushions**

### CODE REVIEW

**Comment by cmitu** [comment]
I have a couple of notes:
 - Not sure about the 
> _Increasing this amount will ***harm*** emulation performance._
 I mean, a higher `gpu_mem` **can** affect emulation, by 'stealing' the ARM memory leaving less for V3D and the system.
- For the Pi4, there were a couple of topics in the forums (and in the RasPI forums) about recommending a `gpu_mem` of `288` or even `320`, needed for certain 4k videos. LibreElec had this setting some time ago (see [this config](https://github.com/LibreELEC/LibreELEC.tv/commit/ae4f088114f8061fda41bee50d199befd6022f6e#diff-33f564797d46a74193635f33443b0ea76db860d18f1fc9b83d359a0653729fff)) and it might be true still for the Kodi version we have.  
  Note that (now) LibreElec switched to a newer Kodi and to a (pure) KMS setup, which doesn't use the MMAL based decoder and instead use the ARM memory, so they removed the `gpu_mem` configuration ([here](https://github.com/LibreELEC/LibreELEC.tv/commit/c67367f611c63d438240131710a834964a3f6b00#diff-33f564797d46a74193635f33443b0ea76db860d18f1fc9b83d359a0653729fff) and [here](https://github.com/LibreELEC/LibreELEC.tv/commit/2db13635e0d0f3b0397d40752a5758013ea1d6e1#diff-33f564797d46a74193635f33443b0ea76db860d18f1fc9b83d359a0653729fff), [here](https://github.com/LibreELEC/LibreELEC.tv/commit/1c483722b6e919e55406bd70f4e56481fd439445#diff-33f564797d46a74193635f33443b0ea76db860d18f1fc9b83d359a0653729fff)). We should probably revise this info if/when we're going to switch to a similar config (or Kodi is upgraded to 19).

**Comment by dankcushions** [comment]
I think "will" should be "can" as you'd probably have to increase it very significantly before causing a problem. Have changed that wording.

i accept that it would need adjusting for Kodi, but I don't use it nor fully understand what gpu_mem does on a pi4 in the technical sense - allocates memory to certain video/camera processes I believe. Can you please draft a Kodi note?

**Comment by cmitu** [comment]
> i accept that it would need adjusting for Kodi, but I don't use it nor fully understand what gpu_mem does on a pi4 in the technical sense - allocates memory to certain video/camera processes I believe. Can you please draft a Kodi note?

Maybe something like https://retropie.org.uk/docs/Pi4/#using-4k-video-with-kodivlc

**Comment by dankcushions** [comment]
Thanks - how about now?

**Comment by cmitu** [comment]
Looks good to me !

**Pull request merged**
