### PR TITLE
Update RetroAchievements.md

### PR DESCRIPTION
**Pull request by bverc**
Update RetroAchievements.md to include updated instructions for setting notification size after the introduction of menu widgets

### CODE REVIEW

**Comment by cmitu** [comment]
Thanks for the contribution.

I have only one comment - can you still keep the note about `video_font_size` configuration option and add a note about not being the default ? It's not the default in recent versions of RetroArch, but it applies in cases when the user disables the gfx style widgets.

**Comment by bverc** [comment]
I have made the suggested change. However, I'm not certain of terminology. What are the older style notifications called? There doesn't seem to much documentation on this anywhere I can see.

**Comment by cmitu** [comment]
> What are the older style notifications called?

I think the terminology is _OSD messages/notifications_, _onscreen notifications_. You can refer to them as the _old style [OSD] notifications_ instead of 'standard notifications' (menu widgets is now the standard).

**Comment by bverc** [comment]
Done. Thanks for your help.

**Pull request merged**
