### PR TITLE
Update Updating-RetroPie.md

### PR DESCRIPTION
**Pull request by GregariousJB**
Just going to update this screenshot of retropie_setup to the latest version and ask a few questions.

That whole section beneath the screenshot feels overkill. It's listing every single option in the script instead of just keeping it relevant to the point of this page - updating. I'm still new to this project so correct me if I'm wrong, but doesn't the `Update` section  update ***everything***, including the retropie-setup script and all optional packages? If so, ideally only that should be mentioned.

After that, I think the "Manage packages" section can certainly be mentioned to update individual things, but with the knowledge that it's not necessary if the user uses the "Update" function (again, correct me if I'm wrong). I think I can cut down a lot of fluff on this page.

I'm not overly familiar with Binary and Source updates so I'd just leave that alone.

I wonder if the Making a Backup section should be it's own page, but not a big deal.  After having used win32diskimager once to try to get 40 GB of a 128 GB SD card flashed onto a 64 GB SD card and failing, I'll probably want to mention that. And after doing some Googlin' and seeing how other people circumvent this SD card limitation by just backing up certain folders, like `/home/pi/RetroPie/roms` and `/opt/retropie/configs/all/emulationstation/gamelists`, I'm thinking of mentioning all the "important" folders but I don't know all of them yet. WinSCP is great at gzipping folders that can be dragged anywhere for backups. Might be worth a mention: https://i.imgur.com/iK5EUsR.png

Thoughts?

On a side note, I'm just randomly picking pages. Is there a page you can think of that needs more help than most? My discord is `GregariousJB#6350` if you're feeling chatty. If not, no worries. I'm content with these little Github love letters if you are.

### CODE REVIEW

**Comment by dankcushions** [comment]
> That whole section beneath the screenshot feels overkill. It's listing every single option in the script instead of just keeping it relevant to the point of this page - updating.

i think it's a little tricky as this page also deals with installing additional packages/using the the package manager in general. Perhaps 'Updating-RetroPie' is the wrong title but it would break all in-the-wild references to this page if we change it. I believe we could get rid of all but the sections related to the above, though:
> Update: This will update the RetroPie-Setup script and all installed packages.
> Manage Packages: This will allow you to install and update individual emulators, ports, controller drivers (like the ps3 or xboxdrv) other optional packages.
> Update RetroPie-Setup Script: Updates the RetroPie-Setup script to the latest version.

FYI there is slightly different summaries of these functions in the [help text in the code](https://github.com/RetroPie/RetroPie-Setup/blob/4902a43749073dbf9146c9cfad4a2b56db7a5839/scriptmodules/admin/setup.sh#L595-L604) - it would be nice to add any information missing from the docs.

> I wonder if the Making a Backup section should be it's own page

i think if it was fleshed out, and linked to here, then yes.

> On a side note, I'm just randomly picking pages.

thanks for your help! personally i think almost every page would benefit from fresh eyes. my personal 'hit list' includes:
https://retropie.org.uk/docs/Overclocking/
https://retropie.org.uk/docs/Optimization-for-Nintendo-64/
https://retropie.org.uk/docs/Dreamcast/
However that's just the areas I personally feel most familiar with, and have changes in mind.

**Comment by GregariousJB** [comment]
> thanks for your help! personally i think almost every page would benefit from fresh eyes. my personal 'hit list' includes:
> https://retropie.org.uk/docs/Overclocking/
> https://retropie.org.uk/docs/Optimization-for-Nintendo-64/
> https://retropie.org.uk/docs/Dreamcast/
> However that's just the areas I personally feel most familiar with, and have changes in mind.

Welcome. I've been able to play some beloved games from my youth thanks to Retropie, so I'm hoping to pay it back by helping in a small way here.

Ok, based on what you said I'm content with just leaving the Updating Retropie page alone for now.

Interesting you mentioned those three pages, because I've recently needed to use them as well, but I've defaulted to using videos from [ETA PRIME](https://www.youtube.com/channel/UC_0CVCfC_3iuHqmyClu59Uw) for Pi 4 stuff since our Overclocking page isn't updated for it yet. On that note, how do you guys feel about linking directly to videos by ETA PRIME? They seem very professionally done and could help more users other than myself.

And for Dreamcast, lr-flycast seems to be working very well for the few ROMs I've tried to the point where I'm wondering if it should be installed by default for all Retropie users (at least for the Pi 4), but that's a different discussion.

As for n64 Optimization, agreed. The first link from the Mupen64 developer is a deleted post, but Removeddit brings it back: https://www.removeddit.com/r/RetroPie/comments/6se5nj/why_n64_emulation_on_the_pi_isnt_so_great_from_a/ (is it still relevant? It's 3 years old), and the default n64 emulator - lr-mupen64plus - seems vastly inferior to GLideN64. So unless there's an internal plan to change the default emulator, mentioning switching to GLideN64 as a first priority should probably be on the page somewhere. 

That's all I can think of at the moment.

**Comment by joolswills** [comment]
I would prefer not to link to these videos in our documentation.

**Comment by cmitu** [comment]
[..]
> 
> After that, I think the "Manage packages" section can certainly be mentioned to update individual things, but with the knowledge that it's not necessary if the user uses the "Update" function (again, correct me if I'm wrong). I think I can cut down a lot of fluff on this page.

Packages can be updated individually, and this is a routine support response for forum posts which might need just an update of the package (i.e. package was rebuild) or maybe just an update to the RetroPie-Setup script and then a source update for a single package (if something was corrected in the script in the RetroPie repository). This avoids a full update, especially if the user has source installs, which makes it tedious to do a full upgrade.


> I wonder if the Making a Backup section should be it's own page, but not a big deal. 

 Yes, splitting it to another page is a good idea.

> After having used win32diskimager once to try to get 40 GB of a 128 GB SD card flashed onto a 64 GB SD card and failing, I'll probably want to mention that.

Isn't that already covered in backup Option no. 1  ?

> And after doing some Googlin' and seeing how other people circumvent this SD card limitation by just backing up certain folders, like `/home/pi/RetroPie/roms` and `/opt/retropie/configs/all/emulationstation/gamelists`, I'm thinking of mentioning all the "important" folders but I don't know all of them yet

Option .2 for backups shows those folders - bios, configs, roms. Maybe they need more _oomph_.

> On that note, how do you guys feel about linking directly to videos by ETA PRIME? They seem very professionally done and could help more users other than myself.

No.

**Comment by GregariousJB** [comment]
> Yes, splitting it to another page is a good idea.

This is all you guys if you want to create a "Backups" page. Guessing that needs to be done in the Mkdocs yml. In the meantime, if you want, you could consider adding a "How to Contribute" page as well. I could start filling it out with what I've learned thus far (header #s, using Github to make pull requests, relative page links like `[Overclocking](overclocking)`, etc.

Also while you're in there, [this has been bugging me as well](https://i.imgur.com/VFR3o5b.png). Thinking we should put those two pages near each other, or perhaps combine them.

> Option .2 for backups shows those folders - bios, configs, roms. Maybe they need more _oomph_.

Yeah, it just shows the folder names, but not where they're located. Thought I might include their absolute paths as well.

> No.

lol ok. But I can't promise I won't use his knowledge to work on the Overclocking page if it comes down to it 😄 . I've overclocked two Pi 4s and couldn't boot after doing it with a Pi 3, so he's got way more experience than I, and likely all of you for that matter. If I touched that page it would be very carefully.

You're welcome to merge this small pull request at any time. I'll mess with this page later.

My brain keeps returning to wanting an easier way to discuss this stuff, either in a Discord's #wiki channel or on the forum, but you guys don't have a Discord and the forum doesn't seem to have a clear section for wiki discussions. Ideas and Development? Looks like there's an [unofficial Discord at r/SBCGaming](https://www.reddit.com/r/RetroPie/comments/787xl9/unofficial_retropie_discord_server/). Wish you guys had an official Discord.

**Comment by HerbFargus** [comment]
Here's the markdown style guide that I had scratched out a while back. May need some further tweaks but it's there. https://gist.github.com/HerbFargus/97a290247924ef6966ecb240797174a6

**Comment by dankcushions** [comment]
> I've overclocked two Pi 4s and couldn't boot after doing it with a Pi 3, so he's got way more experience than I, and likely all of you for that matter.

my experience is the opposite! his past overclocking guides and retropie guides have often been full of misinformation and dangerous/wrong tweaks. his pi4 install guide continues to cause us grief. i expect your pi3 didn't boot because of his bad advice - I seem to remember he had a fairly insane suggested overclocks.

overclocking is a strange one as it's something the community is seemingly obsessed with, but not with benchmarking and evaluating the actual benefits. for example, overclocking CPU on pi4 is pointless for things like N64, psx, and most of the other things people care about, and gpu overclocking provides limited benefit also. similar story with pi3 (though GPU overclocking can help certain things).

overclocking pi3/4 to the hilt isn't something i see much justification for, but we spend a lot of time supporting people who have random crashes who later nonchalantly mention that they are running an extreme overlock (perhaps after following ETA's guide) 🙄  My hope for the overclocking page would be to frame in in this way, beyond just instructions.

>  Ideas and Development

yes, i think that's the place for discussing improvements to the docs.

**Comment by GregariousJB** [comment]
> his past overclocking guides and retropie guides have often been full of misinformation and dangerous/wrong tweaks. his pi4 install guide continues to cause us grief.

Wow seriously? They're always highly recommended on reddit, and [he seems to be including benchmarking](https://www.youtube.com/watch?v=TwDbQ26_Mp8).

Is that the general consensus? You guys don't like ETA PRIME's instructions on overclocking? If that's true I'll defer to your judgement, and I'm thinking I shouldn't touch the Overclocking page at all.

> i expect your pi3 didn't boot because of his bad advice

I suspect it had more to do with me not having any cooling on the Pi 3 whatsoever, active or passive. Both Pi 4s have come out (seemingly) beautifully using his instruction, but I didn't do the distro upgrade to cap out at 2.1 GHz. I just gave them a small boost to ~1.6 GHz.

**Comment by dankcushions** [comment]
> Wow seriously? They're always highly recommended on reddit

not on the retropie subreddit - at least, not by the regulars/mods. although in any case i wouldn't put too much stake into what is said about retropie on reddit - the best info/support is always at https://retropie.org.uk/forum/ 😉 

> Is that the general consensus? 

here, yes.

**Comment by cmitu** [comment]
> Here's the markdown style guide that I had scratched out a while back.

Restored the style [page](https://github.com/RetroPie/RetroPie-Docs/blob/master/docs/Style-Guide.md), for now I've added it under the _About_ navigation section.

**Comment by GregariousJB** [comment]
Just noticed a "Transferring Roms" section in the First Installation page as well: https://retropie.org.uk/docs/First-Installation/#transferring-roms

Just skimming through this page, I'm seeing a lot of fat that can be trimmed and made future-proof so it doesn't need to be updated after each new Raspberry Pi model. Being a relatively new user/installer on 3 different Pis in the last few weeks, I'm thinking I can help quite a bit on this page from the perspective of a person who has needed to use it, and those of you with more experience can fill in the gaps. I recognize this page's importance.

Also, 
> You're welcome to merge this small pull request at any time. I'll mess with this page later.

Thanks for letting me discuss some important things with you guys in a less-than-typical way. Maybe I'll ~~wine and complain about~~ try using the forum from now on. 

<sub>Or maybe not.</sub>

**Pull request merged**
