### PR TITLE
Fix segacd page

### PR DESCRIPTION
**Pull request by bspeakmon**
* Fix a misformatted list in the Sega CD doc that was bothering me :)

### CODE REVIEW

**Comment by cmitu** [comment]
> * Create a `Pipfile/Pipfile.lock` pair to automate local `mkdocs` environment setup.

I wouldn't include this here.

> * Specify the `black` palette for the theme, which gets links to show up as a distinct color in text

We actually have our own colors set in the custom CSS - I added back the link color to it.

**Comment by bspeakmon** [comment]
> I wouldn't include this here.

Would you mind explaining to me why? It lets new contributors like me set up a working python env to run mkdocs locally and see how it really looks (viewing the rendered markdown in github doesn't actually match how it looks once deployed). also, you can set up CI/CD to automatically deploy changes to the live site -- we do this for mkdocs sites at work. 

Still your call though.
 
> We actually have our own colors set in the custom CSS - I added back the link color to it.

no probs, I reverted my theme change.

**Comment by cmitu** [comment]
> Would you mind explaining to me why? It lets new contributors like me set up a working python env to run mkdocs locally and see how it really looks (viewing the rendered markdown in github doesn't actually match how it looks once deployed). also, you can set up CI/CD to automatically deploy changes to the live site -- we do this for mkdocs sites at work.

Installing locally is easy enough through `pip` (and can be done once) and I prefer not to add an additional dependency on `pipenv`. @joolswills any thoughts on this ?

**Comment by joolswills** [comment]
Since we generate the docs from RetroPie-Setup it would seem like unnecessary duplication for now so I'd prefer not to include this.

**Comment by joolswills** [comment]
However I may consider moving docs generation if others would prefer it. But it's not a high priority with other ongoing tasks.

**Comment by bspeakmon** [comment]
no probs, I'll keep the pipfiles for my own use, but I've taken them out of the MR. thanks for the explanation.

**Pull request merged**
