### PR TITLE
Update Nintendo-DS.md

### PR DESCRIPTION
**Pull request by Unknown-programer**
I have tested lr desume with an overclock and a few games are playable.

### CODE REVIEW

**Comment by cmitu** [comment]
Too vague and overclocking is not an option for all users.
What games did you try and ran ok ?

**Comment by Unknown-programer** [comment]
The Lego Star Wars tan at playable speeds with overclock. There was some lag though. 
Games with graphics similar to New Super Mario Bros will also run ok.

**Comment by cmitu** [comment]
I'll have to take a look and test myself.
I'd rather not recommend something that's partially working and only with overclocking and give users the false impression that it works.

**Comment by cmitu** [comment]
OK, this seems right. Thanks for the addition !

**Pull request merged**
